api_encryption_key: "your-api_encryption_key"
ota_password: "your-ota_password"
wifi_password: "your-wifi_password"
ap_password: "your-ap-ap_password"
static_ip_env_sen55: "your-static_ip_env_sen55"
gateway: "your-gateway"
subnet: "your-subnet"
dns1: "your-dns1"
